//    /var/www/nextcloud/config/config.php
<?php
$CONFIG = array (
  'instanceid' => '<redacted>',
  'passwordsalt' => '<redacted>',
  'secret' => '<redacted>',
  'trusted_domains' =>
  array (
    0 => '192.168.0.123',
    1 => 'nextcloud.duckdns.org',
  ),
  'datadirectory' => '/mnt/purple/ncdata/data',
  'dbtype' => 'mysql',
  'version' => '26.0.0.11',
  'overwrite.cli.url' => 'https://nextcloud.duckdns.org/',
  'htaccess.RewriteBase' => '/',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'administrator',
  'dbpassword' => '<redacted>',
  'installed' => true,
  'logfile' => '/var/log/nextcloud.log',
  'default_phone_region' => 'HR',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis-server.sock',
    'port' => 0,
    'dbindex' => 0,
    'password' => '',
    'timeout' => 0.5,
  ),
  'enable_file_metadata' => true,
  'enable_previews' => true,
  'preview_concurrency_new' => 4,
  'preview_max_x' => 1440,
  'preview_max_y' => 1440,
  'preview_ffmpeg_path' => '/usr/bin/ffmpeg',
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\TXT',
    1 => 'OC\\Preview\\MarkDown',
    2 => 'OC\\Preview\\OpenDocument',
    3 => 'OC\\Preview\\StarOffice',
    4 => 'OC\\Preview\\MSOffice2003',
    5 => 'OC\\Preview\\MSOffice2007',
    6 => 'OC\\Preview\\MSOfficeDoc',
    7 => 'OC\\Preview\\PDF',
    8 => 'OC\\Preview\\Postscript',
    9 => 'OC\\Preview\\Image',
    10 => 'OC\\Preview\\XBitmap',
    11 => 'OC\\Preview\\Photoshop',
    12 => 'OC\\Preview\\Illustrator',
    13 => 'OC\\Preview\\JPEG',
    14 => 'OC\\Preview\\PNG',
    15 => 'OC\\Preview\\BMP',
    16 => 'OC\\Preview\\GIF',
    17 => 'OC\\Preview\\SVG',
    18 => 'OC\\Preview\\TIFF',
    19 => 'OC\\Preview\\Movie',
    20 => 'OC\\Preview\\MP4',
    21 => 'OC\\Preview\\M4V',
    22 => 'OC\\Preview\\AVI',
    23 => 'OC\\Preview\\MOV',
    24 => 'OC\\Preview\\QT',
    25 => 'OC\\Preview\\MKV',
    26 => 'OC\\Preview\\MTS',
    27 => 'OC\\Preview\\M2TS',
    28 => 'OC\\Preview\\TS',
    29 => 'OC\\Preview\\HEIC',
    30 => 'OC\\Preview\\WMV',
    31 => 'OC\\Preview\\ASF',
    32 => 'OC\\Preview\\3GP',
    33 => 'OC\\Preview\\WEBM',
    34 => 'OC\\Preview\\VOB',
    35 => 'OC\\Preview\\MP3',
    36 => 'OC\\Preview\\EPS',
    37 => 'OC\\Preview\\ICO',
    38 => 'OC\\Preview\\PS',
    39 => 'OC\\Preview\\WMF',
    40 => 'OC\\Preview\\WEBP',
    41 => 'OC\\Preview\\FLV',
    42 => 'OC\\Preview\\RAW',
  ),
  'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
  'memories.vod.ffprobe' => '/usr/bin/ffprobe',
  'memories.vod.path' => '/var/www/nextcloud/apps/memories/exiftool-bin/go-vod-amd64',
  'memories.vod.disable' => false,
  'memories.gis_type' => 1,
  'memories.exiftool' => '/var/www/nextcloud/apps/memories/exiftool-bin/exiftool-amd64-glibc',
  'maintenance' => false,
);
